---
applications:
- name: help-to-heat-staging
  routes:
  - route: help-to-heat-staging.london.cloudapps.digital
    protocol: http1
  processes:
  - type: web
    instances: 1
    memory: 1024M
    disk_quota: 4092M
    health-check-type: port
